server:
  servlet:
    context-path: '/spring-security-rest-api'

feature:
  beta:
    enabled: false

cors:
  origin:
    patterns: "https://example.com,http://example.com,https://*.example.com,http://*.example.com"