name: 'CI-deploy-main-to-aws-development'

on:
  workflow_dispatch:
  repository_dispatch:
    types: do-deploy-main-to-aws-development

jobs:
  deploy-main-to-aws-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # default 360
    steps:
    - uses: actions/checkout@v1
      with:
        ref: 'main'
    - name: Install Java 21
      uses: actions/setup-java@v1
      with:
        java-version: '21'
        java-package: jdk
        architecture: x64
    - name: 'Install dependencies'
      run: |
        ./ci-install-dependencies.sh
    - name: 'CI Build Command'
      timeout-minutes: 20
      run: |
        ./ci-build.sh
    - name: 'CI Build Docker Command'
      timeout-minutes: 20
      run: |
        ./ci-build-docker.sh
    - name: 'CI Push Docker Command'
      timeout-minutes: 20
      env:
        ENVIRONMENT: 'development'
        APPLICATION_NAME: 'spring-security-rest-api'
        DOCKER_AWS_ACCOUNT_ID: ${{ vars.AwsAccountId }}
        DOCKER_AWS_REGION: 'eu-west-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.AwsAccessKeyId }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AwsSecretAccessKey }}
        AWS_DEFAULT_REGION: 'eu-west-2'
        AWS_DEFAULT_OUTPUT: 'json'
      run: |
        ./ci-push-docker.sh